### ISSUE TITLE
Access logs not emitted?

### ISSUE THREAD

**Issue by shamus** [cloudfoundry/tomcat-cnb#5]
I'm using an image created via `pack` and this build pack. Providing `$BPL_TOMCAT_ACCESS_LOGGING=y` when launching a container should result in access logs being sent to stdout. However, when I access the running application, I do not see any access logs.

Running ps reveals that `-Daccess.logging.enabled=enabled` is provided when the app is launched. Additionally, the following line appears in the logs:

Tomcat Access Logging enabled

Any thoughts on what might be wrong?

cc @cloudfoundry/cf-uaa

**Comment by nebhale** [comment]
Yep, definitely a problem here.  Looking it over now.
