### ISSUE TITLE
Document how to enable access logging

### ISSUE THREAD

**Issue by andrewedstrom** [cloudfoundry/tomcat-cnb#6]
It appears after https://github.com/cloudfoundry/tomcat-cnb/issues/5 that it is now possible to enable access logging for the image. However when we `cat /layers/org.cloudfoundry.tomcat/catalina-base/logs/access_log.2020-01-10` after accessing our app, we don't see any logs reported. 

How can we build or run the image so that it actually has access logs? It would be great to have some documentation for that.

**Comment by nebhale** [comment]
Access logging does not got to log files within the container, as the filesystem would be ephemeral within the container and lost immediately on exit.  As with CF, access logs are printed to the console and each platform collects the output of the console in its own way.

**Comment by andrewedstrom** [comment]
We are fairly confident that the logs are also not going to standard out in our case.

We started the image with `docker run -e LOGIN_CONFIG_URL=classpath:required_configuration.yml -e BPL_TOMCAT_ACCESS_LOGGING=true -p 9090:8080 cfidentity/uaa`, and the first line of output is 
> Tomcat Access Logging enabled
 
Which based on https://github.com/cloudfoundry/tomcat-cnb/blob/21b67ea43ab6c3d6e6f69004c004feab7f944f3f/base/base.go#L123-L129 makes us think that we have enabled logging.

However, when we access our app  by going to http://localhost:9090/login, no output appears in either the window where we started the container, or in `docker logs <container-name>`.

**Comment by nebhale** [comment]
During staging, what version of the Tomcat buildpack is used?

```
[builder] Cloud Foundry Apache Tomcat Buildpack 1.1.62
[builder]   Apache Tomcat Support 3.3.0: Contributing to layer
[builder]   Contributing Configuration
[builder]     Copying context.xml to /layers/org.cloudfoundry.tomcat/catalina-base/conf
[builder]     Copying logging.properties to /layers/org.cloudfoundry.tomcat/catalina-base/conf
[builder]     Copying server.xml to /layers/org.cloudfoundry.tomcat/catalina-base/conf
[builder]     Copying web.xml to /layers/org.cloudfoundry.tomcat/catalina-base/conf
[builder]   Contributing Access Logging Support
[builder]     Reusing cached download from buildpack
[builder]     Copying to /layers/org.cloudfoundry.tomcat/catalina-base/lib
[builder]     Writing .profile.d/access-logging
[builder]   Contributing Lifecycle Support
[builder]     Reusing cached download from buildpack
[builder]     Copying to /layers/org.cloudfoundry.tomcat/catalina-base/lib
[builder]   Contributing Logging Support
[builder]     Reusing cached download from buildpack
[builder]     Copying to /layers/org.cloudfoundry.tomcat/catalina-base/bin
[builder]     Writing /layers/org.cloudfoundry.tomcat/catalina-base/bin/setenv.sh
[builder]   Mounting application at /layers/org.cloudfoundry.tomcat/catalina-base/webapps/ROOT
[builder]     Writing CATALINA_BASE to launch
[builder]   Apache Tomcat 9.0.30: Contributing to layer
[builder]     Reusing cached download from buildpack
[builder]     Extracting to /layers/org.cloudfoundry.tomcat/tomcat
[builder]     Writing CATALINA_HOME to launch
[builder]   Process types:
[builder]     task:   catalina.sh run
[builder]     tomcat: catalina.sh run
[builder]     web:    catalina.sh run
```

**Comment by nebhale** [comment]
In line with the title of the issue (but not the direction of the discussion), there is a need to improve the documentation on that flag and the others available at runtime.  I'll do that work as part of this.
